// @flow
import {StyleSheet, ListViewBase} from 'react-native';
import {Images, Metrics, Fonts, Colors} from '../../theme';

export default StyleSheet.create({
  container: {
    backgroundColor: Colors.Glitter,
    flex: 1,
    //  justifyContent: "center"
  },
  servicebox: {
    height: Metrics.screenHeight * 0.2,
    width: Metrics.screenWidth * 0.37,
    backgroundColor: '#fff',
    marginVertical: Metrics.ratio(17),
    paddingHorizontal: Metrics.ratio(15),
    borderRadius: Metrics.ratio(15),
    elevation: 5,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
  },
  textmiddle: {
    textAlign: 'center',
  },
  submitBtn: {
    backgroundColor: '#FF3600',
    paddingVertical: Metrics.ratio(10),
    // alignItems: 'center',
    borderRadius: Metrics.screenWidth * 0.35,
  },
  submitBtnText: {
    fontSize: Metrics.ratio(14),
    color: '#fff',
    // justifyContent: "center",
    // textAlignVertical: "center"
    textAlign: 'center',
  },
  textInput: {
    height: Metrics.ratio(40),
    backgroundColor: '#fff',
    width: Metrics.screenWidth * 0.45,
    paddingHorizontal: Metrics.ratio(10),
    marginBottom: Metrics.ratio(15),
    borderRadius: Metrics.screenWidth * 0.5,
    borderWidth: 1,
    borderColor: '#F3F4F8',
    color: '#81788B',
    justifyContent: 'center',
  },
  textInputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Metrics.ratio(10),
    marginTop: Metrics.ratio(25),
    marginBottom: 20,
    borderRadius: Metrics.screenWidth * 0.5,
    borderWidth: 1,
    borderColor: '#F3F4F8',
    color: '#81788B',
  },
  ImageStyle: {
    padding: 10,
    margin: 5,
    height: 25,
    width: 25,
    resizeMode: 'stretch',
    alignItems: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7);',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    width: Metrics.screenWidth * 0.8,
    // height: Metrics.screenHeight * 0.4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  crossImageStyle: {
    height: 20,
    width: 20,
    alignSelf: 'flex-end',
    marginTop: 15,
  },
  modalText: {
    textAlign: 'center',
    fontSize: Metrics.ratio(20),
    marginTop: Metrics.ratio(-10),
  },
  submitBtnView: {
    backgroundColor: '#FF3600',
    paddingVertical: Metrics.ratio(7),
    alignItems: 'center',
    marginTop: Metrics.ratio(10),
    marginBottom: Metrics.ratio(10),
    width: Metrics.screenWidth * 0.73,
    borderRadius: Metrics.screenWidth * 0.35,
    borderWidth: 1,
    borderColor: '#FF3600',
    color: '#81788B',
    justifyContent: 'center',
    elevation: 5,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.17,
    shadowRadius: 1.0,
  },
});
